spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}


server:
  port: 19100

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.example.user: DEBUG

token:
  expiration-time: ${JWT_TOKEN_EXPIRE}
  secret-key: ${JWT_SECRET_KEY}

google:
  email: ${GOOGLE_EMAIL}
  secret-key: ${GOOGLE_SECRET_KEY}

kakao:
  client_id: ${KAKAO_API_KEY}
  redirect_uri: http://localhost:8080/api/auth/kakao/callback