spring:
  # config:
  #   import: optional:file:.env.local[.properties]
  application:
    name: coupon-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      username: ${DEV_REDIS_USERNAME}
      password: ${DEV_REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        show_sql: true # sql 로깅
  #        format_sql: true # SQL 문 정렬하여 출력
  #        highlight_sql: true # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /coupon-service/v3/api-docs
  swagger-ui:
    path: /coupon-service/swagger-ui.html

log:
  logstash:
    host: ${LOG_STASH_HOST}
    port: ${LOG_STASH_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

